version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=moonlitdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/moonlitdb
      - FINNHUB_KEY=${FINNHUB_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_URL=http://localhost:3000/moonlit/
      - REACT_APP_API_URL=http://localhost:5000/
      - REACT_APP_API_UPDATE=45000
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
