FROM python:slim

WORKDIR /app

COPY . .

RUN apt-get update \
    && apt-get install -y gcc python3-dev libpq-dev \
    && apt-get clean

RUN pip install -r requirements.txt

ENV FLASK_APP=run.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
